import { PageConfig } from "./pageConfig";
import { applyContentLayer } from "./contentLayer";
import {
  awards,
  cta,
  commonFaq,
  commonSteps,
  defaultCases as cases,
  geoBlock,
  pickThematicCases,
  pricing3,
  pricing5,
  team,
  trustMetrics,
} from "./sharedContent";

const aiRating = {
  type: "aiRating" as const,
  title: "Рейтинг брендов в AI-ответах",
  items: [
    {
      brand: "vsemanipulyatory.ru",
      score: "+21,21%",
      source: "GEO/AI-кейс из 04-kontent/kejsy.md",
      note: "Perplexity 43%, Алиса 27%, AI Overview 12%; требуется финальная ручная сверка.",
    },
    {
      brand: "mrmattress.ru",
      score: "+21,33%",
      source: "GEO/AI-кейс из 04-kontent/kejsy.md",
      note: "Используется как проверяемая строка виджета, без новых выдуманных метрик.",
    },
    {
      brand: "stynergy.ru",
      score: "+13,21%",
      source: "GEO/AI-кейс из 04-kontent/kejsy.md",
      note: "Опциональный блок помечен как требующий проверки человеком.",
    },
  ],
};

const quiz = {
  type: "quiz" as const,
  steps: [
    { question: "Что важнее сейчас?", options: ["Больше заявок", "Снизить стоимость лида", "Навести порядок в сайте"] },
    { question: "С чем уже работаете?", options: ["SEO", "Карты и площадки", "Пока без системы"] },
    { question: "Какой темп нужен?", options: ["Аккуратно", "Быстро", "Сначала аудит"] },
  ],
  finalText: "Готово. Оставьте контакт, и команда соберёт рекомендации под вашу ситуацию.",
};

const calculator = {
  type: "calculator" as const,
  resultLabel: "Условный потенциал заявок",
  steps: [
    { label: "Спрос", options: [{ label: "Низкий", value: 15 }, { label: "Средний", value: 35 }, { label: "Высокий", value: 70 }] },
    { label: "Состояние сайта", options: [{ label: "Нужен ремонт", value: 10 }, { label: "База есть", value: 25 }, { label: "Готов к росту", value: 45 }] },
    { label: "Конкуренция", options: [{ label: "Мягкая", value: 30 }, { label: "Средняя", value: 20 }, { label: "Жёсткая", value: 10 }] },
  ],
};

const serviceLinks = [
  { label: "SEO под ключ", href: "/seo-pod-kljuch/", price: "от 45 тыс ₽/мес" },
  { label: "AI-SEO продвижение", href: "/ai-seo-prodvizhenie/" },
  { label: "SEO для WordPress", href: "/seo-prodvizhenie-wordpress/" },
  { label: "Продвижение стоматологии", href: "/prodvizhenie-stomatologii/" },
  { label: "Корпоративные сайты", href: "/prodvizhenie-korporativnyh-sajtov/" },
  { label: "Геомаркетинг", href: "/geomarketing/" },
  { label: "Авито под ключ", href: "/prodvizhenie-na-avito-pod-kljuch/" },
  { label: "Создание сайтов", href: "/sozdanie-sajtov/" },
];

export const pages: Record<string, PageConfig> = {
  home: {
    slug: "home",
    title: "SEO Jazz — система привлечения клиентов",
    description: "SEO Jazz строит SEO, GEO/AI, площадки и сайты как систему заявок, а не набор позиций.",
    template: "Главная",
    source: "04-kontent/kejsy.md + 01-strategicheskiy-brif.md",
    crumbs: [],
    blocks: [
      {
        type: "hero",
        eyebrow: "SEO Jazz",
        title: "107 650 заявок из поиска и AI-каналов как система, а не набор строчек в отчёте",
        text: "Собираем SEO, GEO/AI, контент, разработку и площадки в одну систему, где главный ориентир — заявки, выручка и понятный следующий шаг.",
        metrics: trustMetrics,
        actions: cta,
      },
      { type: "pricing", tiers: pricing5 },
      { type: "links", title: "Направления", links: serviceLinks },
      geoBlock,
      { type: "cases", cases },
      { type: "trust", metrics: trustMetrics },
      { type: "faq", items: commonFaq },
      { type: "leadForm", title: "Получить аудит" },
    ],
  },
  uslugi: {
    slug: "uslugi",
    title: "Услуги SEO Jazz — продвижение, AI-SEO, площадки и ниши под заявки",
    description: "Все услуги SEO Jazz: SEO под ключ, AI-SEO/GEO, ниши, CMS, типы сайтов, карты и площадки.",
    template: "Хаб услуг",
    source: "04-kontent/uslugi.md",
    crumbs: [{ label: "Услуги" }],
    blocks: [
      { type: "hero", eyebrow: "Хаб услуг", title: "Услуги SEO Jazz: система привлечения клиентов, а не набор строчек", text: "Разводящая страница по кластерам услуг с видимой перелинковкой и коммерческими CTA.", actions: cta },
      { type: "links", title: "Кластеры услуг", links: serviceLinks },
      { type: "included", title: "Подход", items: [{ title: "Экономика", text: "Работаем от заявок, выручки и стоимости лида." }, { title: "Структура", text: "Собираем посадочные, хабы и перелинковку по матрице." }, { title: "Доверие", text: "Используем только подтверждённые кейсы и трастовые цифры." }] },
      { type: "faq", items: commonFaq },
      { type: "leadForm", title: "Получить прогноз по услуге" },
    ],
  },
  seoPodKljuch: {
    slug: "seo-pod-kljuch",
    title: "SEO под ключ — заявки и продажи под одной командой, а не позиции",
    description: "Продвижение сайта под ключ: стратегия, техника, контент, ссылки и аналитика в одной команде.",
    template: "Формат услуги (Г1)",
    source: "04-kontent/seo-pod-kljuch.md",
    crumbs: [{ label: "Услуги", href: "/uslugi/" }, { label: "SEO под ключ" }],
    blocks: [
      { type: "hero", eyebrow: "Формат услуги", title: "SEO под ключ: заявки и выручка под одной командой, а не строчки в выдаче", text: "Одна команда отвечает за стратегию, технику, контент, ссылки и аналитику.", metrics: [{ value: "45 тыс ₽", label: "старт тарифа" }, { value: "KPI", label: "по заявкам и лидам" }], actions: cta },
      { type: "utp", items: [{ title: "Один KPI", text: "Не дробим ответственность между подрядчиками." }, { title: "Полный цикл", text: "От аудита до контента и внедрения." }, { title: "Прозрачная аналитика", text: "Смотрим заявки, лиды и стоимость обращения." }] },
      { type: "fit", fit: [{ title: "Нужен системный рост" }, { title: "Есть спрос и конкуренция" }], notFit: [{ title: "Нужны гарантии позиций" }, { title: "Нет готовности внедрять правки" }] },
      { type: "pricing", tiers: pricing3 },
      calculator,
      { type: "steps", steps: commonSteps },
      { type: "included", title: "Что входит", items: [{ title: "Техника" }, { title: "Семантика и структура" }, { title: "Контент" }, { title: "Ссылки и доверие" }, { title: "Аналитика" }, { title: "GEO/AI-готовность" }] },
      { type: "cases", cases },
      { type: "reviews", items: [{ title: "Отзывы", text: "Блок готов к подключению реальных отзывов из подтверждённых источников." }] },
      { type: "team", people: team },
      { type: "awards", items: awards },
      { type: "guarantees", items: [{ title: "KPI в договоре", text: "Фокус на заявках, лидах и стоимости заявки." }] },
      { type: "faq", items: commonFaq },
      { type: "leadMagnet", title: "Скачать логику аудита", text: "Лид-магнит подключён как отдельный блок и переиспользуется в форматах услуг.", action: { label: "Запросить аудит", href: "#lead" } },
      { type: "links", title: "Связанные форматы", links: serviceLinks.slice(0, 5) },
      geoBlock,
      { type: "leadForm", title: "Обсудить SEO под ключ" },
    ],
  },
  aiSeo: {
    slug: "ai-seo-prodvizhenie",
    title: "AI-SEO продвижение — органика и ответы нейросетей в одной системе",
    description: "AI-SEO: продвигаем сайт одновременно в поиске и в ответах нейросетей.",
    template: "GEO/AI (Г2)",
    source: "04-kontent/ai-seo-prodvizhenie.md",
    crumbs: [{ label: "Услуги", href: "/uslugi/" }, { label: "AI-SEO продвижение" }],
    blocks: [
      { type: "hero", eyebrow: "GEO / AI", title: "AI-SEO: продвижение в поиске и нейросетях как единая система", text: "Страница собрана по вопросному hero, answer-first логике и блоку видимости в AI.", metrics: [{ value: "+21,33%", label: "пример прироста AI-видимости" }, { value: "FAQPage", label: "answer-first структура" }], actions: cta },
      { type: "counters", metrics: [{ value: "+21,21%", label: "vsemanipulyatory.ru" }, { value: "+21,33%", label: "mrmattress.ru" }, { value: "+13,21%", label: "stynergy.ru" }] },
      { type: "problems", title: "Почему бренд не цитирует AI", items: [{ title: "Нет сущностей", text: "Нейросетям сложно понять бренд, услуги и доказательства." }, { title: "Слабая структура ответа", text: "Контент не отвечает коротко и прямо." }, { title: "Мало доверия", text: "Не хватает источников, кейсов и связей." }] },
      { type: "included", title: "6 направлений работы", items: [{ title: "Entities" }, { title: "Schema" }, { title: "FAQ" }, { title: "Сравнения" }, { title: "Кейсы" }, { title: "Перелинковка" }] },
      { type: "comparison", columns: ["SEO", "GEO", "AI-SEO"], rows: [{ label: "Канал", values: ["Поиск", "Ответы нейросетей", "Поиск + AI"] }, { label: "Фокус", values: ["Страницы", "Сущности", "Система ответов"] }] },
      { type: "cases", cases },
      { type: "steps", steps: commonSteps },
      { type: "pricing", tiers: pricing3 },
      { type: "proven", items: [{ title: "Данные из реестра", text: "GEO/AI-кейсы берутся только из kejsy.md." }] },
      { type: "team", people: team },
      { type: "awards", items: awards },
      { type: "guarantees", items: [{ title: "Без выдуманного citation rate", text: "Новые проценты не придумываются; спорные кейсы идут на проверку." }] },
      { type: "reviews", items: [{ title: "Отзывы ЛПР", text: "Место под подтверждённые отзывы, когда они будут добавлены в контентный слой." }] },
      { type: "faq", items: commonFaq },
      { type: "links", title: "Связанные GEO-услуги", links: [{ label: "GEO-продвижение", href: "/geo-prodvizhenie/" }, { label: "AEO-продвижение", href: "/aeo-prodvizhenie/" }, { label: "LLM-оптимизация", href: "/llm-optimizacija/" }] },
      { type: "leadMagnet", title: "Проверка AI-видимости", text: "CTA на аудит присутствия бренда в ответах нейросетей.", action: { label: "Проверить видимость", href: "#lead" } },
      aiRating,
      { type: "leadForm", title: "Запросить AI-SEO аудит" },
    ],
  },
  stomatologia: {
    slug: "prodvizhenie-stomatologii",
    title: "SEO-продвижение стоматологии — пациенты, заявки и доверие",
    description: "SEO для стоматологии: локальный спрос, E-E-A-T/YMYL, контент и заявки.",
    template: "Ниша (Г3)",
    source: "04-kontent/prodvizhenie-stomatologii.md",
    crumbs: [{ label: "Услуги", href: "/uslugi/" }, { label: "Продвижение стоматологии" }],
    blocks: [
      { type: "hero", eyebrow: "Ниша", title: "SEO-продвижение сайта стоматологии: пациенты из поиска, карт и AI-ответов", text: "Шаблон ниши учитывает экономику клиники, доверие врача, локальный выбор и YMYL-ограничения.", metrics: [{ value: "от 65 тыс ₽", label: "рекомендуемый старт" }, { value: "3-6 мес", label: "первый цикл работ" }], actions: cta },
      { type: "problems", title: "Контекст ниши", items: [{ title: "Пациент выбирает осторожно" }, { title: "Важны врачи и доказательства" }, { title: "Карты влияют на звонки" }] },
      { type: "included", title: "E-E-A-T / YMYL", items: [{ title: "Экспертность врачей" }, { title: "Безопасные формулировки" }, { title: "Отзывы и локальные факторы" }] },
      { type: "team", people: team },
      { type: "steps", steps: commonSteps },
      { type: "pricing", tiers: pricing3 },
      { type: "utp", items: [{ title: "Локальный спрос" }, { title: "Медицинская семантика" }, { title: "Доверие к клинике" }] },
      { type: "cases", cases: cases.slice(0, 1) },
      { type: "awards", items: awards },
      { type: "included", title: "Локальное SEO и каталоги", items: [{ title: "Карты" }, { title: "Справочники" }, { title: "Репутация" }] },
      quiz,
      { type: "links", title: "Смежные услуги", links: serviceLinks },
      { type: "faq", items: commonFaq },
      geoBlock,
      { type: "leadForm", title: "Получить план для клиники" },
    ],
  },
  wordpress: {
    slug: "seo-prodvizhenie-wordpress",
    title: "SEO-продвижение сайта на WordPress — заявки, а не позиции",
    description: "Продвижение сайта на WordPress: плагины, скорость, дубли, семантика и контент.",
    template: "CMS (Г4)",
    source: "04-kontent/seo-prodvizhenie-wordpress.md",
    crumbs: [{ label: "Услуги", href: "/uslugi/" }, { label: "SEO для WordPress" }],
    blocks: [
      { type: "hero", eyebrow: "CMS", title: "SEO-продвижение сайта на WordPress: чтобы движок приводил заявки", text: "Гайд+услуга: устраняем типовые ограничения WordPress и собираем рост по заявкам.", actions: cta },
      quiz,
      { type: "problems", title: "Задачи по WordPress", items: [{ title: "Дубли и индексация" }, { title: "Скорость и плагины" }, { title: "Структура посадочных" }] },
      { type: "fit", fit: [{ title: "WordPress уже выбран" }, { title: "Нужна SEO-система" }], notFit: [{ title: "Нельзя внедрять правки" }, { title: "Нужна только настройка одного плагина" }] },
      { type: "included", title: "Что входит", items: [{ title: "Yoast/RankMath" }, { title: "Техника" }, { title: "Контент" }, { title: "Скорость" }] },
      { type: "steps", steps: commonSteps },
      { type: "pricing", tiers: pricing3 },
      { type: "links", title: "Матрица CMS", links: [{ label: "SEO по CMS", href: "/seo-prodvizhenie-po-cms/" }, { label: "SEO на Битрикс", href: "/seo-prodvizhenie-bitrix/" }, { label: "SEO на Tilda", href: "/seo-prodvizhenie-tilda/" }] },
      { type: "cases", cases },
      { type: "counters", metrics: trustMetrics },
      { type: "awards", items: awards },
      { type: "faq", items: commonFaq },
      geoBlock,
      { type: "leadForm", title: "Проверить WordPress-сайт" },
    ],
  },
  corporate: {
    slug: "prodvizhenie-korporativnyh-sajtov",
    title: "SEO-продвижение корпоративного сайта — B2B-заявки, а не позиции",
    description: "SEO для корпоративного сайта: B2B-семантика, ЛПР, доверие и длинный цикл сделки.",
    template: "Тип сайта (Г5)",
    source: "04-kontent/prodvizhenie-korporativnyh-sajtov.md",
    crumbs: [{ label: "Услуги", href: "/uslugi/" }, { label: "Корпоративные сайты" }],
    blocks: [
      { type: "hero", eyebrow: "Тип сайта", title: "SEO-продвижение корпоративного сайта: поток B2B-заявок, а не строчки в выдаче", text: "Шаблон под тип сайта: ЛПР, доверие, длинный цикл сделки и доказательства экспертизы.", metrics: [{ value: "от 65 тыс ₽", label: "для B2B-роста" }], actions: cta },
      { type: "problems", title: "Почему корпоративный сайт не привлекает", items: [{ title: "Нет ответа для ЛПР" }, { title: "Слабые доказательства" }, { title: "Размытая структура услуг" }] },
      { type: "included", title: "6 направлений", items: [{ title: "Семантика B2B" }, { title: "Контент" }, { title: "E-E-A-T" }, { title: "Кейсы" }, { title: "Аналитика" }, { title: "GEO/AI" }] },
      { type: "comparison", columns: ["Базовое SEO", "B2B-система"], rows: [{ label: "Фокус", values: ["Запросы", "ЛПР и заявки"] }, { label: "Доверие", values: ["Минимум", "Кейсы, команда, факты"] }] },
      { type: "cases", cases: pickThematicCases("prodvizhenie-korporativnyh-sajtov") },
      { type: "steps", steps: commonSteps },
      { type: "pricing", tiers: pricing3.slice(1) },
      { type: "team", people: team },
      { type: "proven", items: [{ title: "Подтверждено данными", text: "Кейсы и цифры берутся из реестра, без выдуманных результатов." }] },
      { type: "guarantees", items: [{ title: "Гарантии по KPI", text: "Заявки, лиды и стоимость заявки вместо обещания мест в выдаче." }] },
      { type: "faq", items: commonFaq },
      geoBlock,
      { type: "links", title: "Перелинковка типов", links: [{ label: "Сайты услуг", href: "/prodvizhenie-sajtov-uslug/" }, { label: "Интернет-магазины", href: "/prodvizhenie-internet-magazinov/" }, { label: "Сайты-каталоги", href: "/prodvizhenie-sajtov-katalogov/" }] },
      { type: "leadForm", title: "Запросить B2B-аудит" },
    ],
  },
  sozdanieSajtov: {
    slug: "sozdanie-sajtov",
    title: "Создание сайтов под ключ — сайт, который приносит заявки",
    description: "Разрабатываем сайты под ключ и сразу под SEO и нейросети.",
    template: "Создание сайтов (Г6)",
    source: "04-kontent/sozdanie-sajtov.md",
    crumbs: [{ label: "Создание сайтов" }],
    blocks: [
      { type: "hero", eyebrow: "Разработка", title: "Создание сайтов под ключ: сайт, который приводит заявки, а не просто существует", text: "Разработка сразу учитывает SEO, GEO/AI-готовность, структуру спроса и будущую аналитику.", actions: [{ label: "Начать проект", href: "#lead" }, { label: "Смотреть кейсы", href: "/cases/", variant: "secondary" }] },
      { type: "links", title: "Якорная навигация", links: [{ label: "Виды сайтов", href: "#types" }, { label: "Этапы", href: "#steps" }, { label: "Стоимость", href: "#price" }] },
      { type: "fit", fit: [{ title: "Нужен сайт под заявки" }, { title: "Нужно сразу заложить SEO" }], notFit: [{ title: "Нужна только картинка без стратегии" }] },
      { type: "included", title: "Портфолио", items: [{ title: "Интернет-магазины" }, { title: "Корпоративные сайты" }, { title: "Лендинги" }, { title: "Калькуляторы и формы" }] },
      { type: "utp", items: [{ title: "Польза" }, { title: "Структура" }, { title: "Готовность к росту" }] },
      { type: "cases", cases },
      { type: "steps", steps: [...commonSteps, { title: "Запуск", text: "Передаём сайт с базовой аналитикой и точками дальнейшего роста." }] },
      { type: "pricing", tiers: [{ name: "Проект", price: "по расчёту", description: "Суммы и сроки уточняются по задаче, как отмечено в контент-файле.", features: ["Структура", "Дизайн", "Разработка", "SEO/GEO-готовность"], action: { label: "Рассчитать", href: "#lead" }, featured: true }] },
      { type: "included", title: "Что включает", items: [{ title: "Хостинг" }, { title: "SSL" }, { title: "Формы" }, { title: "SEO-основа" }] },
      { type: "reviews", items: [{ title: "Отзывы и счётчики", text: "Блок подключён как переиспользуемый элемент шаблона разработки." }] },
      { type: "faq", items: commonFaq },
      geoBlock,
      { type: "links", title: "Дополнительные услуги", links: serviceLinks },
      { type: "leadForm", title: "Рассчитать проект" },
    ],
  },
  geomarketing: {
    slug: "geomarketing",
    title: "Геомаркетинг — клиенты из карт и справочников, а не позиции",
    description: "Геомаркетинг под ключ: Яндекс.Карты, 2ГИС, Google Maps, локальное SEO и репутация.",
    template: "Площадки-гео (Г7а)",
    source: "04-kontent/geomarketing.md",
    crumbs: [{ label: "Услуги", href: "/uslugi/" }, { label: "Геомаркетинг" }],
    blocks: [
      { type: "hero", eyebrow: "Карты и площадки", title: "Геомаркетинг: система клиентов из карт и справочников", text: "Единая работа с геосервисами, локальным SEO, репутацией и AI-выдачей.", actions: cta },
      { type: "fit", fit: [{ title: "Сети и филиалы" }, { title: "Локальные услуги" }], notFit: [{ title: "Нужны накрутки отзывов" }] },
      { type: "included", title: "Что входит", items: [{ title: "Яндекс.Карты" }, { title: "2ГИС" }, { title: "Google Maps" }, { title: "Яндекс Бизнес" }, { title: "Локальное SEO" }, { title: "Репутация" }] },
      { type: "steps", steps: commonSteps },
      { type: "problems", title: "Путь клиента", items: [{ title: "Найти рядом" }, { title: "Сравнить отзывы" }, { title: "Позвонить или построить маршрут" }] },
      { type: "utp", items: [{ title: "Звонки" }, { title: "Визиты" }, { title: "Филиальная аналитика" }] },
      { type: "reviews", items: [{ title: "Отзывы сетей", text: "Только реальные отзывы и легальная модерация." }] },
      { type: "leadMagnet", title: "Аудит присутствия", text: "Проверим карточки, справочники, отзывы и локальные точки роста.", action: { label: "Запросить аудит", href: "#lead" } },
      quiz,
      { type: "faq", items: commonFaq },
      geoBlock,
      { type: "leadForm", title: "Получить аудит присутствия" },
    ],
  },
  avito: {
    slug: "prodvizhenie-na-avito-pod-kljuch",
    title: "Продвижение на Авито под ключ — заявки и заказы, а не просто показы",
    description: "Ведём Авито под ключ: упаковка профиля, оптимизация объявлений, автозагрузка и аналитика.",
    template: "Площадки-Авито (Г7б)",
    source: "04-kontent/prodvizhenie-na-avito-pod-kljuch.md",
    crumbs: [{ label: "Услуги", href: "/uslugi/" }, { label: "Продвижение на Авито" }],
    blocks: [
      { type: "hero", eyebrow: "Авито", title: "Продвижение на Авито под ключ: поток заявок и заказов", text: "Шаблон площадки строится вокруг объёма объявлений, упаковки профиля, заявок и правил площадки.", actions: cta },
      { type: "included", title: "Услуги", items: [{ title: "Упаковка профиля" }, { title: "Оптимизация объявлений" }, { title: "Автозагрузка" }, { title: "Аналитика" }] },
      { type: "pricing", tiers: [{ name: "Старт", price: "по объёму", features: ["Малый каталог", "Базовая упаковка"], action: { label: "Рассчитать", href: "#lead" } }, { name: "Профи", price: "по объёму", features: ["Регулярное ведение", "Оптимизация"], action: { label: "Рассчитать", href: "#lead" }, featured: true }, { name: "Максимум", price: "по объёму", features: ["Много объявлений", "Масштабирование"], action: { label: "Рассчитать", href: "#lead" } }] },
      { type: "steps", steps: [...commonSteps, { title: "Масштаб", text: "Расширяем категории и связку с другими площадками." }] },
      { type: "team", people: team },
      { type: "counters", metrics: trustMetrics },
      { type: "cases", cases },
      { type: "leadMagnet", title: "Бриф по Авито", text: "Бриф-документ подключён как лид-магнит шаблона.", action: { label: "Получить бриф", href: "#lead" } },
      { type: "leadForm", title: "Рассчитать продвижение на Авито" },
      { type: "faq", items: [...commonFaq, { question: "Вы используете серые схемы?", answer: "Нет. В контентных рисках прямо зафиксирована работа по правилам площадки, без накруток и серых схем." }] },
    ],
  },
  cases: {
    slug: "cases",
    title: "Кейсы SEO Jazz",
    description: "Реальные кейсы и трастовые факты SEO Jazz из подтверждённого реестра.",
    template: "Кейсы (агрегатор)",
    source: "04-kontent/kejsy.md",
    crumbs: [{ label: "Кейсы" }],
    blocks: [
      { type: "hero", eyebrow: "Кейсы", title: "Кейсы SEO Jazz: реальные метрики из подтверждённого реестра", text: "Агрегатор показывает только факты из kejsy.md; индивидуальные страницы кейсов исключены из демо-батча.", metrics: trustMetrics, actions: cta },
      { type: "cases", cases },
      { type: "included", title: "Карта кейсов", items: [{ title: "Медицина" }, { title: "Стройка и производство" }, { title: "Авто и логистика" }, { title: "B2B и IT" }, { title: "Недвижимость" }, { title: "GEO/AI" }] },
      { type: "links", title: "Куда применить опыт", links: serviceLinks },
      { type: "leadForm", title: "Подобрать релевантный кейс" },
    ],
  },
};

export function getPageConfig(slug: keyof typeof pages) {
  return applyContentLayer(pages[slug]);
}
